services:

  nginx: 
    container_name: nginx
    image: nginx:alpine
    ports:
      - "8080:80"
    depends_on:
      - app
      - db
    volumes:
      - ./src/var/www:/var/www/html
      - ./nginx/conf.d/:/etc/nginx/conf.d

  db:
    image: mysql
    container_name: mysql
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=paradise-hotel-laravel
      - MYSQL_ROOT_PASSWORD=password

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
      - "3400:80"
    depends_on:
      - db

  app:
    container_name: app
    build:
      context: ./src
      dockerfile: Dockerfile
    volumes:
      - ./src:/var/www/html
    depends_on:
      - db
